# Welcome to Serverless!
#
# For full config options, check the kubeless plugin docs:
#    https://github.com/serverless/serverless-kubeless
#
# For documentation on kubeless itself:
#    http://kubeless.io

# Update the service name below with your own service name
service: testsls

# Please ensure the serverless-kubeless provider plugin is installed globally.
# $ npm install -g serverless-kubeless
#
# ...before installing project dependencies to register this provider.
# $ npm install

provider:
  name: kubeless
  runtime: nodejs6
  namespace: testsls

plugins:
  - serverless-kubeless

functions:
  capitalize:
    handler: handler.capitalize
    events:
      - trigger: 'photosi_message.undefined_directory:message.user_updated'

  dummy:
    handler: handler.dummy
    events:
      - trigger: 'photosi_message.undefined_directory:message.user_updated.business'

  erroraccioa:
    handler: handler.erroraccio
    events:
      - trigger: 'photosi_message.undefined_directory:message.user_deleted'

  realsum:
    handler: handler.realSum
    events:
      - http:
          path: /PhotosiMessage.UndefinedDirectory:Request.RealSum$
